apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Optional, Kubernetes will assign one if not specified

